### ISSUE TITLE
key word: override

### ISSUE THREAD

**Issue by wangxiaoying** [octol/vim-cpp-enhanced-highlight#19]
The highlight of the new key word of c++11: override is still not supported.
![screenshot from 2015-11-19 14 18 08](https://cloud.githubusercontent.com/assets/5569610/11263731/6890e420-8ec8-11e5-8928-6f53c5be90a1.png)

**Comment by octol** [comment]
As far as I know, the override keyword is supported by stock vim. I'm running version 7.4.826 (Debian) and I see the override keyword in the provided cpp.vim.
