### ISSUE TITLE
E28: No such highlight group name: cppStructure

### ISSUE THREAD

**Issue by MarvinCorro** [octol/vim-cpp-enhanced-highlight#26]
Not sure what this means or how to fix it

**Comment by MarvinCorro** [comment]
I just turned off the optional feature and it works

**Comment by pingsoli** [comment]
@MarvinCorro I don't get it, I encounter the same problem, but I don't konw how to deal with it, please help me.

**Comment by MarvinCorro** [comment]
hey @pingsoli sorry I hardly remember what I did and the laptop that I installed this on I no longer have to look at my bashrc file. I think what I did was set all the optional features as listed in the read me to 0. Try that, hope it helps.

**Comment by pingsoli** [comment]
@MarvinCorro, I really appreciate your reply, I have tried it. thanks again.
