### ISSUE TITLE
Highlight newer *_t/*_v/*_* types

### ISSUE THREAD

**Issue by oblitum** [octol/vim-cpp-enhanced-highlight#29]
I've checked that it's not highlighting `enable_if_t` (C++14) nor `is_integral_v` (C++17), there should be more.

**Comment by octol** [comment]
I've merged in #33, does it fix this issue?

**Comment by oblitum** [comment]
@octol hi. It's still missing the C++17 bits.

**Comment by bfrg** [comment]
See pull request [#35](https://github.com/octol/vim-cpp-enhanced-highlight/pull/35).

**Comment by oblitum** [comment]
Indeed #35 seems to cover the remaining bits of this feature request.

**Comment by octol** [comment]
Merged #35
