### ISSUE TITLE
No highlighting for function names beginning with an upper case 

### ISSUE THREAD

**Issue by zachwhaley** [octol/vim-cpp-enhanced-highlight#31]
![screenshot from 2016-08-29 11-59-59](https://cloud.githubusercontent.com/assets/2996465/18059783/3e1c3df0-6de0-11e6-88eb-04984925bac2.png)

Running f4351bac4fb7565cbccc9aff6b97005183abdee3

Seen on NeoVim 0.1.5 and Vim 7.4

**Comment by zachwhaley** [comment]
After running a git bisect, I found this was the offending commit e738b20032441c6f8a0b17d7c0071877154bc61a

**Comment by octol** [comment]
Thanks for tracking down the regression. This behaviour certainly needs to be fixed.

**Comment by zachwhaley** [comment]
No problem :)

Disabling this [line](https://github.com/octol/vim-cpp-enhanced-highlight/blob/master/after/syntax/cpp.vim#L45) is what is causing the issue, btw

**Comment by xfrings** [comment]
I'm currently using the below lines to fix upper case function highlight issue and disabling Octol's lines. This is a standard C function parser.
```
syn match cUserFunction "\<\h\w*\>\(\s\|\n\)*("me=e-1 contains=cType,cDelimiter,cDefine
syn match cUserFunctionPointer "(\s*\*\s*\h\w*\s*)\(\s\|\n\)*(" contains=cDelimiter,cOperator

hi def link cUserFunction cFunction
hi def link cUserFunctionPointer cFunction
```

**Comment by octol** [comment]
Ok so I've started looking into this, but locally on my machine running Vim 8.0 the above example works fine for me...

    VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 05 2016 03:34:23)
    Included patches: 1-22

**Comment by octol** [comment]
Ok sorry now I see it, it's only when `g:cpp_class_scope_highlight = 1`.
