### ISSUE TITLE
Vundle installation command is wrong

### ISSUE THREAD

**Issue by Mmollle** [octol/vim-cpp-enhanced-highlight#37]
Hey,

I just want to inform that "Plugin 'octol/vim-cpp-enhanced-highlight'" does not install the plugin, atleast not for me. It asks for username and password, implying it doesnt find the repository at all.

But by adding .git at the end, I could install it just fine. As such:

Plugin 'octol/vim-cpp-enhanced-highlight.git'

**Comment by dawikur** [comment]
That's weird. It is fine for me without the ```.git``` suffix. Do you have maybe some local changes in your clone if repo?

**Comment by octol** [comment]
Thanks for filing the issue. I've not been able to reproduce it locally so for now I'll close it. If more people are having this issue then we can reopen.
