### ISSUE TITLE
HIghlight bug?

### ISSUE THREAD

**Issue by maekawatoshiki** [octol/vim-cpp-enhanced-highlight#38]
- after 2nd line, all highlighted like string literal..
![a](https://cloud.githubusercontent.com/assets/9913176/20553477/4b839e24-b198-11e6-866d-839dee3bec2b.png)

**Comment by octol** [comment]
Sorry I'm unable to reproduce this locally.

**Comment by maekawatoshiki** [comment]
OK. I'll find what is the cause.
