### ISSUE TITLE
Why is str considered an STL function?

### ISSUE THREAD

**Issue by MichaelMa2014** [octol/vim-cpp-enhanced-highlight#52]
I noticed `str` is highlighted as a `cFunction` [here](https://github.com/octol/vim-cpp-enhanced-highlight/blob/master/after/syntax/cpp.vim#L520). Sorry if the answer is obvious, but why is it?

**Comment by dawikur** [comment]
e.g.
http://en.cppreference.com/w/cpp/io/basic_stringstream/str
