### ISSUE TITLE
Error while opening file

### ISSUE THREAD

**Issue by HackerDeez** [octol/vim-cpp-enhanced-highlight#53]
I get always error

"main.cpp" 30L, 466C                                                                                                                                                    
Error detected while processing /home/somerandomusername/.vim/syntax/cpp.vim:                                                                                                       
line   61:                                                                                                                                                              
E28: No such highlight group name: cppStructure                                                                                                                         
line   80:                                                                                                                                                              
E28: No such highlight group name: cppAccess                                                                                                                            
Press ENTER or type command to continue  

So what can i do ?

**Comment by pingsoli** [comment]
@HackerDeez Have you found the solution ? I got the same error message.
