### ISSUE TITLE
Variable name highlighted wrong

### ISSUE THREAD

**Issue by andreyorst** [octol/vim-cpp-enhanced-highlight#54]
Hello. This is not critical issue, but sometimes variables are colored as functions. I don't see it often, but seems like it represents when variable name is same as some function, `beg` for example. It happens with other names too. For example:
```cpp
template<typename T>
void mysort(T beg, T end) {
    sort(beg, end);
}
```
will be colored in vim like:
![image](https://user-images.githubusercontent.com/19470159/31296531-541cf4d4-aaeb-11e7-8612-918778fffd13.png)
`beg` is the same blue as `sort`, which is confusing when you do a quick lookup on the code. All other variables are always colored white.

I've checked it in other programs and I found that it is a common _problem_.

**Sublime Text**:
![image](https://user-images.githubusercontent.com/19470159/31297253-07c080a8-aaee-11e7-95c4-ed807e13bc36.png)
...

**KDevelop**:
![image](https://user-images.githubusercontent.com/19470159/31297176-b8c71976-aaed-11e7-897e-b43f5f2d423f.png)
interesting...

**Visual Studio Code**:
![image](https://user-images.githubusercontent.com/19470159/31297040-2aee786a-aaed-11e7-9ec1-16d805ab3c92.png)
well, it's just stupid

in **Code::Blocks** it works slightly different from vim:
![image](https://user-images.githubusercontent.com/19470159/31296986-feff17f0-aaec-11e7-9692-878bd52f3af6.png)

**Comment by octol** [comment]
Indeed quite interesting that it happens in other editors/IDEs too.

**Comment by andreyorst** [comment]
what I've found: If you call a variable, for example `main`, it will be colored as a function. So i think that the highlighting system knows all of the standard names, not only for types and constructions like `template`, but a common functions too. But user-defined functions are colored only if they have a parentheses `()` after it. Screenshot to assume everything:
![image](https://user-images.githubusercontent.com/19470159/31585878-d15bbc2c-b1d1-11e7-95ff-1b18b2126aba.png)

The code (to try in other editors, if wanted):
```cpp
void fo() {      // function is highlighted blue
    char maen;   // variable is highlighted white
    maen = 'a';
}

void foo // still a function, but white
() {
    char main;    // a variable, but blue
    main = 'a';
    int template; // variable is colored as template
    template = 5;
    bool vector;
    vector = true;
} 

int main // a main function is known by highlighting system
() {
    fo // fo is not recognized as a function, but it is
    ();
    foo(); // foo is recognozed as a user-defined function brcause of ()
}
```
