### ISSUE TITLE
Nested template function highlighting broken

### ISSUE THREAD

**Issue by kbenzie** [octol/vim-cpp-enhanced-highlight#6]
Since the addition of template highlighting in commit ad4d287 nested templates are being highlighted incorrectly as you can see here.

![broken-template-highlight](https://cloud.githubusercontent.com/assets/1625763/4178048/48d24952-3673-11e4-88a9-fac6355a956e.png)

To be sure this was the problem I checked out bc50a64 which gave the following result.

![no-broken-template-highlighting](https://cloud.githubusercontent.com/assets/1625763/4178046/464b65ce-3673-11e4-89bf-67e06d6e96e6.png)

So it looks like some additional logic is needed to correctly highlight nested templates.

**Comment by unphased** [comment]
So the screenshot provided in the README also suffers from this failure, yes? (the part of the template function arg after `std::is_floating_point`)

Also shouldnt this be (hopefully) easy to fix since its just nesting angle bracket pairs?

**Comment by octol** [comment]
Well nested templates work for most cases with g:cpp_experimental_template_highlight = 1, the exception being constructor initialisation lists like in the above example. This is unfortunate, but I'm not sure this is feasible without a libclang based solution, such as [bbchung/clighter](http://github.com/bbchung/clighter) or [jeaye/color_coded](https://github.com/jeaye/color_coded).

**Comment by unphased** [comment]
Okay, I originally thought that the issue was more simple. 

Still, the parens and angle brackets are properly matched up, this doesnt seem to me like a case of ambiguous grammar that regexes can't handle.

**Comment by octol** [comment]
There are currently two implementations of the template highlight regex, see the README. They are not perfect, but hopefully one of them should be good enough so I'm closing this for now.
