### ISSUE TITLE
Which colorscheme is used in sceenshot?

### ISSUE THREAD

**Issue by PetrusZ** [octol/vim-cpp-enhanced-highlight#65]
I'm using colorscheme tango, it only has simple highlight with cpp-enhanced-highlight
![screenshot from 2018-03-14 16-10-19](https://user-images.githubusercontent.com/4990592/37390286-6634b86c-27a2-11e8-9b91-4093b1024390.png)

**Comment by VentGrey** [comment]
I think it is a monokai/molokai variant.

**Comment by PetrusZ** [comment]
@VentGrey thanks.
